### ISSUE TITLE
改进

### ISSUE THREAD

**Issue by aurexav** [DaseinPhaos/tlborm-chinese#1]
https://daseinphaos.github.io/tlborm-chinese/book/mbe-min-import-export.html

`// X!和Y!并非在此处定义的，但它们**的确**被
// 导出了，即便macros并非pub。`

我猜此处应该是想用 markdown 的加粗吧，不过已经嵌套在 code 当中了，建议手动添加
`<strong></strong>` 标签

**Comment by DaseinPhaos** [comment]
是的，之前用的md->html工具rustbook.exe没有办法很好地识别中文+markdown标识
我好像在src/main.rs里尝试过替换`**`符号，不过似乎遇见了一些其它的问题(替换到不该替换的html片段等)，没有继续

**Comment by acgxv** [comment]
好久没读了回来翻翻，新 issue 就不开了。

1. https://daseinphaos.github.io/tlborm-chinese/book/pat-repetition-replacement.html
2. search **并用用**
3. replace **并用**
